target_link_libraries(
     HeadAnalysis
        glad
        glfw3
        pthread
        dl
        X11
        opencv_core
        opencv_imgproc
        opencv_imgcodecs
        opencv_highgui
        opencv_calib3d
)